### ISSUE TITLE
Error while pushing artifacts to local CAS in bst1

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1448]
```
ERROR:grpc._server:Exception calling application: [Errno 21] Is a directory: '/data/cas/objects/'
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/grpc/_server.py", line 406, in _call_behavior
    return behavior(argument, context), True
  File "/usr/local/lib/python3.7/site-packages/buildstream/_artifactcache/casserver.py", line 381, in GetReference
    self.cas.update_tree_mtime(tree)
  File "/usr/local/lib/python3.7/site-packages/buildstream/_artifactcache/cascache.py", line 638, in update_tree_mtime
    self._reachable_refs_dir(reachable, tree, update_mtime=True)
  File "/usr/local/lib/python3.7/site-packages/buildstream/_artifactcache/cascache.py", line 792, in _reachable_refs_dir
    with open(self.objpath(tree), 'rb') as f:
IsADirectoryError: [Errno 21] Is a directory: '/data/cas/objects/'
```

**Comment by nanonyme** [comment]
I've debugged that this happens because https://github.com/apache/buildstream/blob/45442f963a19a67c9346b53f9f802dc17ed560f2/buildstream/_artifactcache/cascache.py#L488 is invoked when relevant path is empty.

**Comment by nanonyme** [comment]
When this faulty digest is passed to https://github.com/apache/buildstream/blob/45442f963a19a67c9346b53f9f802dc17ed560f2/buildstream/_artifactcache/cascache.py#L392, then we get tree object which points to directory which results in the original error.

**Comment by nanonyme** [comment]
This in turn seems possible if either

1. https://github.com/apache/buildstream/blob/45442f963a19a67c9346b53f9f802dc17ed560f2/buildstream/_artifactcache/cascache.py#L466 this serialization results in empty bytestring
2. https://github.com/apache/buildstream/blob/45442f963a19a67c9346b53f9f802dc17ed560f2/buildstream/utils.py#L498 this helper manages somehow storing data such that it doesn't properly hit filesystem
