### ISSUE TITLE
BUG when trying to access an element through junction on the command line

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1455]
Steps to reproduce:
- have a junction `junction.bst` with `overrides`
- use `bst show` or `bst build` on an element in the junction `junction.bst:element.bst`

I get the following error:

```
    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 258, in override_main
        original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 607, in show
        dependencies = app.stream.load_selection(elements, selection=deps, except_targets=except_)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 166, in load_selection
        target_objects = self._load(
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 1566, in _load
        elements, except_elements, artifacts = self._load_elements_from_targets(
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 1399, in _load_elements_from_targets
        elements, except_elements = self._load_elements([element_names, except_targets])
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 1349, in _load_elements
        elements = self._project.load_elements(targets)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_project.py", line 429, in load_elements
        load_elements = self.loader.load(targets)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_loader/loader.py", line 136, in load
        _junction, name, loader = self._parse_name(target, None)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_loader/loader.py", line 1000, in _parse_name
        loader = self.get_loader(junction_path[-2], provenance_node, load_subprojects=load_subprojects)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_loader/loader.py", line 219, in get_loader
        del self._loader_search_provenances[name]
    KeyError: 'freedesktop-sdk.bst'
```

~~I bisected it to 16e2966dacb716456bb9f105a9c05c4dea024c72 (part of [!2078](https://gitlab.com/BuildStream/buildstream/-/merge_requests/2078))~~ Edit: it seems the elements overrides was implemented after this change.

**Comment by gtristan** [comment]
Observing the time this was filed and the location of `del self._loader_search_provenances[name]` on line 219, this was reported for a version of `loader.py` between d9728b8bad097808c6c102f6ceb0f995382d2da1 and b62dbec4276a25c80ed4977a0e7a405ec62aebd0.

The code has not changed significantly since that time, so I would expect this to still be reproducible, however I cannot reproduce it with tests we currently have.

e.g. the reported scenario can be reproduced (without stacktrace) in the buildstream repository with:

```sh
cd tests/format/junctions/overrides
bst show subproject-with-override.bst:target.bst
```

**Comment by gtristan** [comment]
Looking again at the stack trace, I became suspicious that this bug might be caused by overriding elements in the case of a self junction scenario.

So I'm adding a test for this https://github.com/apache/buildstream/pull/1689 ... unfortunately it still does not reproduce the issue.

**Comment by abderrahim** [comment]
I don't have access to the project that caused this (it's in my home computer and I won't be able to get to it until 5 Aug).

However, continuing on the self-junction idea: the gnome project has a junction to freedesktop-sdk, which has a self-junction. So that may be what you need to do to reproduce.
