### ISSUE TITLE
AssertionErrors when trying to build anything

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1456]
When updating today (this is using 225ae1d446f9fa16a8efe90ddb896d0c1517f0a9), I noticed `AssertionError`s when trying to run a build. Needless to say, this makes bst unusable. The culprit seems to be #1450 since reverting to 1.93.6 works.

```
[09:43:15][        ][    main:core activity                 ] BUG     

    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/scheduler.py", line 423, in real_schedule
        self._sched_queue_jobs()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/scheduler.py", line 363, in _sched_queue_jobs
        queue.enqueue(elements)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 191, in enqueue
        self._enqueue_element(elt)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 380, in _enqueue_element
        status = self.status(element)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/sourcepushqueue.py", line 37, in status
        if element._skip_source_push():
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1962, in _skip_source_push
        return not (self.__sourcecache.has_push_remotes(plugin=self) and self._cached_sources())
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 2281, in _cached_sources
        return self.__sources.cached()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_elementsources.py", line 343, in cached
        assert self._cached is not None
    AssertionError
```

```
[09:43:15][        ][    main:bootstrap/acl.bst             ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError
```

**Comment by juergbi** [comment]
Can you provide additional context from the log? E.g. lines related to `acl.bst` before the BUG message.

**Comment by abderrahim** [comment]
I can try again later, but there is something important I omitted: this happens in non strict mode.

**Comment by abderrahim** [comment]
Here is a full log. I should note it only happens if I have a source cache configured.
```
[19:45:41][        ][    main:core activity                 ] START   Build
[19:45:41][        ][    main:core activity                 ] START   Loading elements
[19:45:41][        ][    main:core activity                 ] SUCCESS Loading elements
[19:45:41][        ][    main:core activity                 ] START   Resolving elements
[19:45:41][        ][    main:bootstrap/build/base-sdk/symlinks.bst] START   Staging local files into CAS
[19:45:41][        ][    main:bootstrap/build/base-sdk/symlinks.bst] SUCCESS Staging local files into CAS
[19:45:41][        ][    main:bootstrap/symlinks.bst        ] START   Staging local files into CAS
[19:45:41][        ][    main:bootstrap/symlinks.bst        ] SUCCESS Staging local files into CAS
[19:45:41][        ][    main:bootstrap/build/stripper.bst  ] START   Staging local files into CAS
[19:45:41][        ][    main:bootstrap/build/stripper.bst  ] SUCCESS Staging local files into CAS
[19:45:41][        ][    main:bootstrap/stripper.bst        ] START   Staging local files into CAS
[19:45:41][        ][    main:bootstrap/stripper.bst        ] SUCCESS Staging local files into CAS
[19:45:41][        ][    main:core activity                 ] SUCCESS Resolving elements
[19:45:41][        ][    main:core activity                 ] START   Initializing remote caches
[19:45:43][        ][    main:core activity                 ] WARNING Failed to initialize remote https://freedesktop-sdk-cache.codethink.co.uk:11001: Configured remote does not implement the Remote Asset Fetch service. Please check remote configuration.
[19:45:43][        ][    main:core activity                 ] SUCCESS Initializing remote caches
[19:45:43][        ][    main:core activity                 ] START   Initializing remote caches
[19:45:43][        ][    main:core activity                 ] SUCCESS Initializing remote caches
[19:45:43][        ][    main:core activity                 ] START   Initializing remote caches
[19:45:43][        ][    main:core activity                 ] SUCCESS Initializing remote caches
[19:45:43][        ][    main:core activity                 ] START   Checking sources
[19:45:43][        ][    main:core activity                 ] SUCCESS Checking sources
[19:45:43][        ][    main:core activity                 ] START   Query cache
[19:45:43][        ][    main:core activity                 ] SUCCESS Query cache
[19:45:43][        ][    main:core activity                 ] START   Preparing work plan
[19:45:43][        ][    main:core activity                 ] SUCCESS Preparing work plan

BuildStream Version 1.93.6+14.g225ae1d44
    Session Start: Monday, 15-03-2021 at 19:45:43
    Project:       freedesktop-sdk (/home/abderrahim/Projects/freedesktop-sdk-bst2)
    Targets:       bootstrap-import.bst

User Configuration
    Configuration File:      /home/abderrahim/.config/buildstream2.conf
    Cache Directory:         /home/abderrahim/.cache/buildstream
    Log Files:               /home/abderrahim/.cache/buildstream/logs
    Source Mirrors:          /data/bstsource
    Build Area:              /home/abderrahim/.cache/buildstream/build
    Strict Build Plan:       No
    Maximum Fetch Tasks:     10
    Maximum Build Tasks:     2
    Maximum Push Tasks:      4
    Maximum Network Retries: 2

Project: freedesktop-sdk

    Project Options
        bootstrap_build_arch: x86_64
        import_bootstrap:     0
        pipewire:             0
        snap_grade:           devel
        target_arch:          x86_64

    Element Plugins
        stack:     core plugin
        manual:    core plugin
        filter:    core plugin
        import:    core plugin
        autotools: core plugin
        script:    core plugin

    Source Plugins
        git_tag: python package 'bst-plugins-experimental 1.93.4' at: /home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages
        ostree:  python package 'bst-plugins-experimental 1.93.4' at: /home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages
        local:   core plugin
        patch:   core plugin
        tar:     core plugin

    Artifact cache servers
      * http://127.0.0.1:11001/
        push: True type: all instance: None
        loaded from: /home/abderrahim/.config/buildstream2.conf [line 13 column 4]
      * https://freedesktop-sdk-cache.codethink.co.uk:11001
        push: False type: all instance: None
        loaded from: project.conf [line 82 column 2]

    Source cache servers
      * http://127.0.0.1:11001/
        push: True type: all instance: None
        loaded from: /home/abderrahim/.config/buildstream2.conf [line 17 column 4]

Pipeline
     waiting ???????????????????????????????????????????????????????????????? bootstrap/build/base-sdk/image-x86_64.bst 
      cached b52cb139ee938204fa8201969952e639222898d6f49d9117334b6a9321369ec7 bootstrap/build/base-sdk/filtered.bst 
      cached f0daa6fca6ff2f904b68bd915cd6bbab09b8dd2b84fac31c57049ada871c0524 bootstrap/build/base-sdk/symlinks.bst 
      cached 5035da8939c311e9eb585d86f6f4b3749751ca17a6e72af4f8ee5299de03f43b bootstrap/build/base-sdk.bst 
      cached a282914586a2bdc576f9eec4cbe28a90625a48f0292713c486a9d8da87552218 bootstrap/gnu-config.bst 
      cached 56d4220b1993e5e153516b3e4cc565eb84a454b0ffdd8d1d63e8d3c581c3eba5 bootstrap/linux-headers.bst 
      cached 018b971428a63af93163f844663e34c166c121848731e46586f6a7cfcb37cc38 bootstrap/symlinks.bst 
      cached 16446b9b0114e51bbef10064a48db7df6ad2f4e4aa0681d882376762d261fb0e bootstrap/build/dwz-build.bst 
      cached b1c810c7ee00d9e2beccdda1fc4d00042b1a92f05cebffb065f9d08952cbd2df bootstrap/build/tools-lib-path.bst 
      cached ac00b7fdb551e53d3950a5f5b18140a75df815b875d9801d23414248f8cf0346 bootstrap/build/elfutils-build.bst 
      cached bd532dd09e7f9bf7e1ae9028d40e39350319f8dbb636d46834c0f5df97a88a5a bootstrap/build/file-stage1.bst 
      cached 3029a07ba6032960b1bef31dc98f48af28396edb04558d31c0dae0a5cf015b7c bootstrap/build/debugedit-build.bst 
      cached 108daff357c2e6e7e50b1a395047e731fe719171f509724e3958cd3fbf63a7d1 bootstrap/build/stripper.bst 
      cached cddf3953db5cac491db50abf13411d46b8420b8b95edd3cd1d45c0cdd8216af4 bootstrap/build/debug-utils.bst 
      cached e0db66480a2bdfc7025ac76d37f55859cc0cd07e1839ec0146276c368ab4afb2 bootstrap/build/binutils-stage1.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/build/gcc-stage1.bst 
      cached db045fa087556b88b4c7ad854932c48f1e7913fb9496ba77a54138c6c2ba2322 bootstrap/glibc.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/build/gcc-stage2.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/attr.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/acl.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/build/ncurses-stage1.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/ncurses.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/readline.bst 
      cached a77eccd61dd4d9a38c4e140755de7fc6c19ef26cab89639fa22548a835caa78f bootstrap/bash.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/zlib.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/binutils-build-deps.bst 
      cached 225cc609339baf0c3b18ca9f4b0f4ec032e41cc580eaa5dd968ae30a1657bb7b bootstrap/binutils.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/bzip2.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/build/coreutils-manpages.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/coreutils.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/elfutils.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/file.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/openssl.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/popt.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/debugedit.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/diffutils.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/dwz.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/findutils.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/gawk.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/gcc.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/pcre.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/grep.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/make.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/sed.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/xz.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/stripper.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/build/glibc-stage1.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/utf-locale.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap/bootstrap.bst 
     waiting ???????????????????????????????????????????????????????????????? bootstrap-import.bst 
===============================================================================
[19:45:43][018b9714][    push:bootstrap/symlinks.bst        ] START   freedesktop-sdk/bootstrap-symlinks/018b9714-push.995045.log
[19:45:43][a2829145][    push:bootstrap/gnu-config.bst      ] START   freedesktop-sdk/bootstrap-gnu-config/a2829145-push.995045.log
[19:45:43][????????][    pull:bootstrap/zlib.bst            ] START   freedesktop-sdk/bootstrap-zlib/????????-pull.995045.log
[19:45:43][56d4220b][    push:bootstrap/linux-headers.bst   ] START   freedesktop-sdk/bootstrap-linux-headers/56d4220b-push.995045.log
[19:45:43][db045fa0][    push:bootstrap/glibc.bst           ] START   freedesktop-sdk/bootstrap-glibc/db045fa0-push.995045.log
[19:45:43][????????][    pull:bootstrap/attr.bst            ] START   freedesktop-sdk/bootstrap-attr/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/zlib.bst            ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 1fa62155 cached
[19:45:43][????????][    pull:bootstrap/ncurses.bst         ] START   freedesktop-sdk/bootstrap-ncurses/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/bzip2.bst           ] START   freedesktop-sdk/bootstrap-bzip2/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/file.bst            ] START   freedesktop-sdk/bootstrap-file/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/attr.bst            ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 3c6e7ab8 cached
[19:45:43][????????][    pull:bootstrap/acl.bst             ] START   freedesktop-sdk/bootstrap-acl/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/popt.bst            ] START   freedesktop-sdk/bootstrap-popt/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/elfutils.bst        ] START   freedesktop-sdk/bootstrap-elfutils/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/ncurses.bst         ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 6e3165ad cached
[19:45:43][????????][    pull:bootstrap/readline.bst        ] START   freedesktop-sdk/bootstrap-readline/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/bzip2.bst           ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact e7b21588 cached
[19:45:43][????????][    pull:bootstrap/openssl.bst         ] START   freedesktop-sdk/bootstrap-openssl/????????-pull.995045.log
[19:45:43][????????][    pull:bootstrap/popt.bst            ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 9573c667 cached
[19:45:43][????????][    pull:bootstrap/readline.bst        ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 53c566f6 cached
[19:45:43][????????][    pull:bootstrap/elfutils.bst        ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 512c3a79 cached
[19:45:43][????????][    pull:bootstrap/file.bst            ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 5b0556ce cached
[19:45:43][????????][    pull:bootstrap/acl.bst             ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact baf7a45f cached
[19:45:43][????????][    pull:bootstrap/openssl.bst         ] INFO    Remote (http://127.0.0.1:11001/) does not have artifact 94a92eb8 cached
[19:45:43][018b9714][    push:bootstrap/symlinks.bst        ] INFO    Pushed data from artifact 018b9714 -> http://127.0.0.1:11001/
[19:45:43][018b9714][    push:bootstrap/symlinks.bst        ] INFO    Remote (http://127.0.0.1:11001/) already has artifact 018b9714 cached
[19:45:43][018b9714][    push:bootstrap/symlinks.bst        ] SKIPPED Push
[19:45:43][a2829145][    push:bootstrap/gnu-config.bst      ] INFO    Pushed data from artifact a2829145 -> http://127.0.0.1:11001/
[19:45:43][a2829145][    push:bootstrap/gnu-config.bst      ] INFO    Remote (http://127.0.0.1:11001/) already has artifact a2829145 cached
[19:45:43][a2829145][    push:bootstrap/gnu-config.bst      ] SKIPPED Push
[19:45:43][        ][    main:core activity                 ] BUG     

    Traceback (most recent call last):
      File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/scheduler.py", line 423, in real_schedule
        self._sched_queue_jobs()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/scheduler.py", line 363, in _sched_queue_jobs
        queue.enqueue(elements)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 191, in enqueue
        self._enqueue_element(elt)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 380, in _enqueue_element
        status = self.status(element)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/sourcepushqueue.py", line 37, in status
        if element._skip_source_push():
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1962, in _skip_source_push
        return not (self.__sourcecache.has_push_remotes(plugin=self) and self._cached_sources())
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 2281, in _cached_sources
        return self.__sources.cached()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_elementsources.py", line 343, in cached
        assert self._cached is not None
    AssertionError

[19:45:43][????????][    main:bootstrap/attr.bst            ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/attr.bst            ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError

[19:45:43][????????][    main:bootstrap/zlib.bst            ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/zlib.bst            ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError

[19:45:43][db045fa0][    main:bootstrap/glibc.bst           ] INFO    Job terminated
[19:45:43][????????][    main:bootstrap/readline.bst        ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/readline.bst        ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError

[19:45:43][????????][    main:bootstrap/bzip2.bst           ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/bzip2.bst           ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError

[19:45:43][????????][    main:bootstrap/acl.bst             ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/acl.bst             ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError

[19:45:43][????????][    main:bootstrap/file.bst            ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/file.bst            ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError

[19:45:43][????????][    main:bootstrap/popt.bst            ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/popt.bst            ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError

[19:45:43][56d4220b][    main:bootstrap/linux-headers.bst   ] INFO    Job terminated
[19:45:43][????????][    main:bootstrap/openssl.bst         ] INFO    Job terminated
[19:45:43][        ][    main:bootstrap/openssl.bst         ] BUG     Unhandled exception in post processing

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/queue.py", line 319, in _job_done
        self.done(job, element, result, status)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 45, in done
        element._load_artifact_done()
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1889, in _load_artifact_done
        assert self.__artifact
    AssertionError
```
