### ISSUE TITLE
BUG when running bst shell --build

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1469]
This seems to be caused by #1450 as well. Running `bst shell --build` in non-strict mode.

```
[10:04:23][        ][    main:core activity                 ] START   Loading elements
[10:04:24][        ][    main:core activity                 ] SUCCESS Loading elements
[10:04:24][        ][    main:core activity                 ] START   Resolving elements
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/build/base-sdk/symlinks.bst] START   Staging local files into CAS
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/build/base-sdk/symlinks.bst] SUCCESS Staging local files into CAS
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/symlinks.bst] START   Staging local files into CAS
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/symlinks.bst] SUCCESS Staging local files into CAS
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/build/stripper.bst] START   Staging local files into CAS
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/build/stripper.bst] SUCCESS Staging local files into CAS
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/stripper.bst] START   Staging local files into CAS
[10:04:24][        ][    main:freedesktop-sdk.bst:bootstrap/stripper.bst] SUCCESS Staging local files into CAS
[10:04:24][        ][    main:core activity                 ] SUCCESS Resolving elements
[10:04:24][        ][    main:core activity                 ] START   Initializing remote caches
[10:04:26][        ][    main:core activity                 ] WARNING Failed to initialize remote https://freedesktop-sdk-cache.codethink.co.uk:11001: Configured remote does not implement the Remote Asset Fetch service. Please check remote configuration.
[10:04:27][        ][    main:core activity                 ] WARNING Failed to initialize remote https://m1-xlarge-x86.gnome.org:11001: Configured remote does not implement the Remote Asset Fetch service. Please check remote configuration.
[10:04:27][        ][    main:core activity                 ] SUCCESS Initializing remote caches
[10:04:27][        ][    main:core activity                 ] START   Query cache
[10:04:27][        ][    main:core activity                 ] SUCCESS Query cache
[10:04:27][        ][    main:core activity                 ] START   Terminating buildbox-casd
[10:04:29][        ][    main:core activity                 ] SUCCESS Terminating buildbox-casd
[10:04:29][        ][    main:core activity                 ] BUG     'NoneType' object has no attribute 'cached'

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 258, in override_main
        original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 722, in shell
        exitcode = app.stream.shell(
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 296, in shell
        missing_deps = [dep for dep in _pipeline.dependencies([element], scope) if not dep._cached()]
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 296, in <listcomp>
        missing_deps = [dep for dep in _pipeline.dependencies([element], scope) if not dep._cached()]
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1187, in _cached
        return self.__artifact.cached()
    AttributeError: 'NoneType' object has no attribute 'cached'
```

**Comment by abderrahim** [comment]
I just got a very similar error doing `bst artifact checkout`

```
[21:55:11][        ][    main:core activity                 ] BUG     'NoneType' object has no attribute 'cached'

    Traceback (most recent call last):
      File "/home/abderrahim/.virtualenvs/bst-master/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 258, in override_main
        original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 1374, in artifact_checkout
        app.stream.checkout(
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 688, in checkout
        uncached_elts = [elt for elt in elements if not elt._cached()]
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/_stream.py", line 688, in <listcomp>
        uncached_elts = [elt for elt in elements if not elt._cached()]
      File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.9/site-packages/buildstream/element.py", line 1187, in _cached
        return self.__artifact.cached()
    AttributeError: 'NoneType' object has no attribute 'cached'
```
