### ISSUE TITLE
bst1: Hang when terminating build

### ISSUE THREAD

**Issue by nanonyme** [apache/buildstream#1479]
I tried to abort build through terminate locally just to get
```
User interrupted with ^C

Choose one of the following options:
  (c)ontinue  - Continue queueing jobs as much as possible
  (q)uit      - Exit after all ongoing jobs complete
  (t)erminate - Terminate any ongoing jobs and exit

Pressing ^C again will terminate jobs and exit

Choice: [continue]: t 
Exception in callback Scheduler._interrupt_event()
handle: <Handle Scheduler._interrupt_event()>
Traceback (most recent call last):
  File "/usr/lib64/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3.9/site-packages/buildstream/_scheduler/scheduler.py", line 481, in _interrupt_event
    self._interrupt_callback()
  File "/usr/lib/python3.9/site-packages/buildstream/_frontend/app.py", line 504, in _interrupt_handler
    choice = click.prompt("Choice:",
  File "/var/home/nanonyme/.local/lib/python3.9/site-packages/click/termui.py", line 168, in prompt
    value = prompt_func(prompt)
  File "/var/home/nanonyme/.local/lib/python3.9/site-packages/click/termui.py", line 143, in prompt_func
    return f(" ")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1: unexpected end of data
```

**Comment by nanonyme** [comment]
Haven't seen this again and no idea how to reproduce so closing.
