### ISSUE TITLE
BUG message when trying to track a junction

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1686]
Trying to `bst source track freedesktop-sdk.bst` on gnome-build-meta commit `d9c77bb1e01cdb233e3c6d4e765ba884697fc8cd` I get the following error:

```
    Traceback (most recent call last):
      File "/home/abderrahimkitouni/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 258, in override_main
        original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_frontend/cli.py", line 953, in source_track
        app.stream.track(elements, selection=deps, except_targets=except_, cross_junctions=cross_junctions)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_stream.py", line 473, in track
        elements = self._load_tracking(
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_stream.py", line 1498, in _load_tracking
        elements, except_elements, artifacts = self._load_elements_from_targets(
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_stream.py", line 1432, in _load_elements_from_targets
        elements, except_elements = self._load_elements([element_names, except_targets])
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_stream.py", line 1382, in _load_elements
        elements = self._project.load_elements(targets)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_project.py", line 441, in load_elements
        elements = [Element._new_from_load_element(load_element, task) for load_element in load_elements]
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_project.py", line 441, in <listcomp>
        elements = [Element._new_from_load_element(load_element, task) for load_element in load_elements]
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/element.py", line 1047, in _new_from_load_element
        element.__load_sources(load_element)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/element.py", line 2503, in __load_sources
        source = project.create_source(meta_source, variables=self.__variables)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_project.py", line 365, in create_source
        return self.source_factory.create(self._context, self, meta, variables)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_pluginfactory/sourcefactory.py", line 51, in create
        source_type, _ = self.lookup(context.messenger, meta.kind, meta.config)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_pluginfactory/pluginfactory.py", line 133, in lookup
        plugin_type, defaults = self._ensure_plugin(kind, provenance_node)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/buildstream/_pluginfactory/pluginfactory.py", line 227, in _ensure_plugin
        source = self._plugin_base.make_plugin_source(
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/pluginbase.py", line 213, in make_plugin_source
        return PluginSource(self, *args, **kwargs)
      File "/home/abderrahimkitouni/.local/lib/python3.9/site-packages/pluginbase.py", line 271, in __init__
        raise RuntimeError('This plugin source already exists.')
    RuntimeError: This plugin source already exists.
```

**Comment by gtristan** [comment]
I'm getting:

```
00:01:17][9a6348f1][   fetch:freedesktop-sdk.bst           ] FAILURE git_tag source at freedesktop-sdk.bst [line 3 column 2]: expected ref 'freedesktop-sdk-22.08beta.1-77-g010e91cdd9ecfd10b74d83af27566f1e5f1dc4f4' was not found in git repository: 'gitlab:freedesktop-sdk/freedesktop-sdk.git'

    Printing the last 20 lines from log file:
    /home/tristan/.cache/buildstream/logs/gnome/freedesktop-sdk/9a6348f1-fetch.560041.log
    ======================================================================
     * [new branch]          willsalmon/bst2-buildbox-diag -> https___gitlab_com_/willsalmon/bst2-buildbox-diag
     * [new branch]          willsalmon/bst2-buildbox-fix -> https___gitlab_com_/willsalmon/bst2-buildbox-fix
     * [new branch]          willsalmon/bst2-buildorder -> https___gitlab_com_/willsalmon/bst2-buildorder
     * [new branch]          willsalmon/bst2-diag -> https___gitlab_com_/willsalmon/bst2-diag
     * [new branch]          willsalmon/bst2-diag-bad -> https___gitlab_com_/willsalmon/bst2-diag-bad
     * [new branch]          willsalmon/bst2-fv -> https___gitlab_com_/willsalmon/bst2-fv
     * [new branch]          willsalmon/bst2-pushonly -> https___gitlab_com_/willsalmon/bst2-pushonly
     * [new branch]          willsalmon/bst2-slang -> https___gitlab_com_/willsalmon/bst2-slang
     * [new branch]          willsalmon/bst2-staging -> https___gitlab_com_/willsalmon/bst2-staging
     * [new branch]          willsalmon/bst2-tmp -> https___gitlab_com_/willsalmon/bst2-tmp
     * [new branch]          willsalmon/bst2-withpip -> https___gitlab_com_/willsalmon/bst2-withpip
     * [new branch]          wip/hadess/update-flatpak-xdg-utils-20.08 -> https___gitlab_com_/wip/hadess/update-flatpak-xdg-utils-20.08
     * [new branch]          wip/pwithnall/appstream -> https___gitlab_com_/wip/pwithnall/appstream
    Running host command /home/tristan/.cache/buildstream/sources/git_tag/gitlab_freedesktop_sdk_freedesktop_sdk_git: /usr/bin/git cat-file -t freedesktop-sdk-22.08beta.1-77-g010e91cdd9ecfd10b74d83af27566f1e5f1dc4f4
    [--:--:--] STATUS  freedesktop-sdk.bst: Running host command

        /usr/bin/git cat-file -t freedesktop-sdk-22.08beta.1-77-g010e91cdd9ecfd10b74d83af27566f1e5f1dc4f4
    fatal: Not a valid object name freedesktop-sdk-22.08beta.1-77-g010e91cdd9ecfd10b74d83af27566f1e5f1dc4f4
    [00:00:03] FAILURE freedesktop-sdk.bst: Fetching from https://gitlab.com/freedesktop-sdk/freedesktop-sdk.git
    [00:01:17] FAILURE [9a6348f1] freedesktop-sdk.bst: git_tag source at freedesktop-sdk.bst [line 3 column 2]: expected ref 'freedesktop-sdk-22.08beta.1-77-g010e91cdd9ecfd10b74d83af27566f1e5f1dc4f4' was not found in git repository: 'gitlab:freedesktop-sdk/freedesktop-sdk.git'
    ======================================================================
```
