### ISSUE TITLE
BUG when using the `storage-service` cache option

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1749]
After adding the `storage-service` cache option, I get the following error. The cache wasn't completely empty (was used as an artifact cache and source cache before) but isn't completely up to date either.

It seems it is trying to push sources for an element without first querying the cache to check that the source is cached.

```
[05:36:29][--:--:--][        ][    main:core activity                 ] BUG     
    Traceback (most recent call last):
      File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
        self._context.run(self._callback, *self._args)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/scheduler.py", line 438, in real_schedule
        self._sched_queue_jobs()
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/scheduler.py", line 378, in _sched_queue_jobs
        queue.enqueue(elements)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/queues/queue.py", line 192, in enqueue
        self._enqueue_element(elt)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/queues/queue.py", line 385, in _enqueue_element
        status = self.status(element)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/queues/sourcepushqueue.py", line 36, in status
        if element._skip_source_push():
      File "/usr/lib/python3.10/site-packages/buildstream/element.py", line 1917, in _skip_source_push
        return not (self.__sourcecache.has_push_remotes(plugin=self) and self._cached_sources())
      File "/usr/lib/python3.10/site-packages/buildstream/element.py", line 2279, in _cached_sources
        return self.__sources.cached()
      File "/usr/lib/python3.10/site-packages/buildstream/_elementsources.py", line 342, in cached
        assert self._cached is not None
    AssertionError
```

**Comment by abderrahim** [comment]
Retrying seems to work :confused:

**Comment by abderrahim** [comment]
So this is caused by the fact that the code paths when using a storage-service and when not using it are different. replacing https://github.com/apache/buildstream/blob/a54f88bc716eff24066f5289cabc911e49ffdb2f/src/buildstream/_stream.py#L209 with `if True:` triggers the same error even without the storage-service.

#1750 should fix this issue.
