### ISSUE TITLE
bst2: Tracking is broken in a different way

### ISSUE THREAD

**Issue by AdrianVovk** [apache/buildstream#1852]
Trying to port carbonOS to bst2. Using `project.refs`. Happens when I use the `docker.io/buildstream/buildstream` image, for both the `dev` and `latest` tags (`bst --version` reports 2.0.1 for both), and both in distrobox and in toolbox.

In an attempt to avoid #1851, I switched to the `docker.io/buildstream/buildstream` image. Instead of the crashes I was getting in the other issue, I get these instead:

```
[00:00:00][????????][   track:pkgs/librsvg.bst              ] BUG     Track

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_scheduler/jobs/job.py", line 438, in child_action
        result = self.child_process()  # pylint: disable=assignment-from-no-return
                 ^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 91, in child_process
        return self._action_cb(self._element)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_scheduler/queues/trackqueue.py", line 65, in _track_element
        return element._track()
               ^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/element.py", line 1390, in _track
        return self.__sources.track(self._get_workspace())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_elementsources.py", line 94, in track
        with self._stage_previous_sources(source) as staging_directory:
      File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_elementsources.py", line 503, in _stage_previous_sources
        with cas.stage_directory(vdir._get_digest()) as tempdir:
      File "/usr/lib64/python3.11/contextlib.py", line 137, in __enter__
        return next(self.gen)
               ^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/buildstream/_cas/cascache.py", line 484, in stage_directory
        response = next(response_stream)
                   ^^^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/grpc/_channel.py", line 475, in __next__
        return self._next()
               ^^^^^^^^^^^^
      File "/usr/local/lib64/python3.11/site-packages/grpc/_channel.py", line 881, in _next
        raise self
    grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
    	status = StatusCode.INTERNAL
    	details = "std::runtime_error exception thrown at [buildboxcasd_fusestager.cpp:148], errMsg = "The FUSE stager child process unexpectedly died with exit code 2""
    	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"std::runtime_error exception thrown at [buildboxcasd_fusestager.cpp:148], errMsg = \"The FUSE stager child process unexpectedly died with exit code 2\"", grpc_status:13, created_time:"2023-08-03T12:21:57.642771105-04:00"}"
```

Offending element:
```
sources:
- kind: git_tag
  url: gnome-git:GNOME/librsvg
  track: main
- kind: cargo
```

Seems to happen, consistently, but to a slightly different set of elements than #1851. However, most of the elements overlap between both issues. Here are the other elements this happens to:

```
sources:
- kind: git_tag
  url: github:zyedidia/micro
- kind: go-vendor
```

```
sources:
- kind: git_tag
  url: gnome-git:GNOME/gnome-tour
  track-extra:
  - gnome-44
  exclude:
  - '*.alpha*'
  - '*.beta*'
  - '*.rc*'
- kind: cargo
```

```
sources:
- kind: git_tag
  url: github:cpuguy83/go-md2man
- kind: patch
  path: patches/md2man/fix-go-ver.patch
- kind: go-vendor
```

```
sources:
- kind: tar
  url: https://static.crates.io/crates/gst-plugin-dav1d/gst-plugin-dav1d-0.10.0.crate
- kind: gen-cargo-lock
- kind: cargo
```

```
sources:
- kind: git_tag
  url: github:systemd/zram-generator
  track: main
  exclude:
  - v*-rc*
  - v*-beta*
- kind: gen-cargo-lock
- kind: cargo
```

I'll note that these all the elements that encounter this bug are using source plugins that need previous sources to be staged (cargo, go-vendor, gen-cargo-lock)

**Comment by AdrianVovk** [comment]
Tracked this one down. The problem is that the official buildstream docker images are missing fuse3...

See: https://gitlab.com/BuildGrid/buildbox/buildbox-casd/-/issues/72

This came up during tracking for the specified elements specifically because they are using source types (`cargo`, `go-vendor`, etc) that require previous sources to be staged.

I'll close this here and open an issue @ the docker repo
