### ISSUE TITLE
Buildstream crashes when instructed to only download from mirrors

### ISSUE THREAD

**Issue by abderrahim** [apache/buildstream#1860]
Trying to add
```
fetch:
  source: mirrors
```
to my buildstream.conf causes buildstream to crash while fetching sources:

```
[00:00:00][400f0914][   fetch:plugins/bst-plugins-experimental.bst] BUG     Fetch
    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/jobs/job.py", line 438, in child_action
        result = self.child_process()  # pylint: disable=assignment-from-no-return
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 91, in child_process
        return self._action_cb(self._element)
      File "/usr/lib/python3.10/site-packages/buildstream/_scheduler/queues/fetchqueue.py", line 75, in _fetch_not_original
        element._fetch(fetch_original=False)
      File "/usr/lib/python3.10/site-packages/buildstream/element.py", line 2207, in _fetch
        self.__sources.fetch()
      File "/usr/lib/python3.10/site-packages/buildstream/_elementsources.py", line 222, in fetch
        self.fetch_sources()
      File "/usr/lib/python3.10/site-packages/buildstream/_elementsources.py", line 251, in fetch_sources
        self._fetch_source(source)
      File "/usr/lib/python3.10/site-packages/buildstream/_elementsources.py", line 432, in _fetch_source
        source._fetch()
      File "/usr/lib/python3.10/site-packages/buildstream/source.py", line 908, in _fetch
        self.__do_fetch()
      File "/usr/lib/python3.10/site-packages/buildstream/source.py", line 1418, in __do_fetch
        raise last_error
    UnboundLocalError: local variable 'last_error' referenced before assignment

```

**Comment by gtristan** [comment]
Hmmmm... strange that I cannot trigger this from either of these tests:
* `tests/frontend/mirror.py::test_mirror_fetch_source[mirrors-success-project-config]`
* `tests/frontend/mirror.py::test_mirror_fetch_source[mirrors-success-user-config]`

Aha I see.

This is happening in the case that:
* We have asked to only use mirrors
* There is a source without a defined mirror

This causes an empty loop... `last_error` should probably be defined earlier *anyway*... but lets see what kind of failure mode we want here, probably we want a more friendly error message in this case.

**Comment by nanonyme** [comment]
@abderrahim which project is this with? Freedesktop-sdk by intent uses one alias without mirror to be able to use strict aliasing without mirroring its own repos.
